### ISSUE TITLE
Support for keyboard shortcuts

### ISSUE THREAD

**Issue by danbim** [iriiiina/JIRA-Issue-Opener#7]
Awesome extension! Love it :)

I'd love it even more if I didn't have to use the mouse. So a really perfect addition would be to have a fixed / configurable keyboard shortcut to open the extensions input field.

**Comment by iriiiina** [comment]
Do you mean to open an extension in the Chrome? This can be done using Chrome standard feature:
* open the extensions tab - chrome://extensions
* link "Configure commands" at the bottom
* choose an extension and type a shortcut

**Comment by danbim** [comment]
Awesome! Didn’t know that :) Thx!
